iotaProject/administrator/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.admin_account, name='index'),
    url(r'logout/', views.logout_user, name='logout'),
    url(r'edit/', views.edit),
    url(r'add_user/', views.add_user),
    url(r'list/', views.list),
    url(r'delete/(?P<user_id>[0-9]+)$', views.delete),
    url(r'edit_user/(?P<user_id>[0-9]+)$', views.edit_user),
    url(r'reports/(?P<report_id>[1-9]+)$', views.reports),
    url(r'reports/custom/', views.reports_filter),
]

iotaProject/iotaProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# https://docs.djangoproject.com/en/1.10/topics/auth/default/#using-the-views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
import teamiota.views
from . import settings
import logging
urlpatterns = [
    url(r'^$', teamiota.views.LoginView.as_view()),
    url('^password_reset/$',
        auth_views.password_reset,
        {
            'template_name': 'passwords/password_reset_form.html',
            'email_template_name': 'passwords/password_reset_email.txt',
            'subject_template_name': 'passwords/password_reset_subject.txt',
            'from_email': settings.DEFAULT_FROM_EMAIL,
        },
        name='password_reset'),
    url('^password_reset/done/$',
        auth_views.password_reset_done,
        {
            'template_name': 'passwords/password_reset_done.html',
        },
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {
            'template_name': 'passwords/password_reset_confirm.html',
        },
        name='password_reset_confirm'),
    url('^reset/done/$',
        auth_views.password_reset_complete,
        {
            'template_name': 'passwords/password_reset_complete.html',
        },
        name='password_reset_complete'),
    url(r'^teamiota/', include('teamiota.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^administrator/', include('administrator.urls')),
]
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

iotaProject/teamiota/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.NormalUsersPortal.as_view(), name='normalUsersPortal'),
    url(r'^NormalUsersPortal/', views.NormalUsersPortal.as_view(), name='normalUsersPortal'),
    url(r'^login/', views.LoginView.as_view(), name='normalUserLogin'),
    url(r'^logout/', views.LogoutView.as_view(), name='normalUserLogout'),
    url(r'^award/(?P<pk>[0-9]+)/', views.AwardView.as_view(), name='awardView'),
    url(r'^revoke/', views.RevokeView.as_view(), name='revokeView'),
    url(r'^DrawnSigSubmitted/',
        views.DrawnSigSubmitted.as_view(),
        name='drawnSigSubmitted'),
]

iotaProject/administrator/forms.py
""" administrator/forms.py """

from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.models import User
from teamiota.models import NormalUser, Award, Location, Department


class AddUserForm(forms.ModelForm):
    """ Form to enter a User's data """

    def __init__(self, *args, **kwargs):
        super(AddUserForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['location'].required = True
        self.fields['department'].required = True
        self.fields['first_name'].required = False
        self.fields['first_name'].help_text = '*optional'
        self.fields['last_name'].required = False
        self.fields['last_name'].help_text = '*optional'

    dept_choices = [(None, "-- Select a Department --")]
    loc_choices = [(None, "-- Select a Location --")]
    try:
        for department in Department.objects.all().order_by('name'):
            dept_choices.append((department.id, department.name))
        for location in Location.objects.all().order_by('name'):
            loc_choices.append((location.id, location.name))
    except:
        pass
    location = forms.ChoiceField(label='location', choices=loc_choices)
    department = forms.ChoiceField(label='department', choices=dept_choices)
    is_admin = forms.BooleanField(label='User is an Admin', required=False)

    class Meta:
        """ Restrict form to username, password, and email fields """

        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name',]
        widgets = {
            'password': forms.PasswordInput(),
            }

    def is_valid(self):
        """ Override validation to enforce unique emails """

        is_valid = super(AddUserForm, self).is_valid()
        
        # Basic validation failed
        if not is_valid:
            return False

        this_email = self.cleaned_data['email']
        this_email_already_exists = False
        try:
            if User.objects.get(email=this_email):
                self.add_error('email', ('{0} is already in use. '
                    'Please choose another email. ').format(this_email))
                this_email_already_exists = True
        except User.DoesNotExist:
            pass

        # return False if email already exists 
        return not this_email_already_exists
        
class EditUserForm(forms.ModelForm):
    """ Edit a teamiota.models.NormalUser """

    def __init__(self, initial_location, initial_department, is_admin, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.fields['location'].required = True
        self.fields['location'].initial = initial_location
        self.fields['department'].required = True
        self.fields['department'].initial = initial_department
        self.fields['first_name'].required = False
        self.fields['first_name'].help_text = '*optional'
        self.fields['last_name'].required = False
        self.fields['last_name'].help_text = '*optional'
        self.fields['is_admin'].initial = is_admin

    dept_choices = [(None, "-- Select a Department --")]
    loc_choices = [(None, "-- Select a Location --")]
    try:
        for department in Department.objects.all().order_by('name'):
            dept_choices.append((department.id, department.name))
        for location in Location.objects.all().order_by('name'):
            loc_choices.append((location.id, location.name))
    except:
        pass
    location = forms.ChoiceField(label='location', choices=loc_choices)
    department = forms.ChoiceField(label='department', choices=dept_choices)
    is_admin = forms.BooleanField(label='User is an Admin', required=False)
    
    class Meta:
        """ Restrict form to exclude auth fields """

        model = User
        fields = ['username', 'first_name', 'last_name',]

class ReportFilterForm(forms.Form):
    """ Get user options for custom reports """

    # Initialize choice arrays for drop-down menus
    type_choices = [(0, "-- All --")]
    dept_choices = [(0, "-- All --")]
    loc_choices = [(0, "-- All --")]
    user_choices = [(0, "-- All --")]

    # Pull choices for drop-downs from model
    # Try/except block required to fix new database migration issue:
    # migrate attempts to run queries before database tables are created
    try:
        for award in Award.objects.all().order_by('awardType'):
            type_choices.append((award.id, award.awardType))

        for department in Department.objects.all().order_by('name'):
            dept_choices.append((department.id, department.name))

        for location in Location.objects.all().order_by('name'):
            loc_choices.append((location.id, location.name))

        for normal_user in NormalUser.objects.filter(isAdmin=False)\
            .order_by('nickname'):
            user_choices.append((normal_user.id, normal_user.nickname))
    except:
        pass

    # Form fields
    award_type = forms.ChoiceField(label='Award Type', choices=type_choices)
    from_user = forms.ChoiceField(label='User', choices=user_choices)
    from_dept = forms.ChoiceField(label='Department', choices=dept_choices)
    from_location = forms.ChoiceField(label='Location', choices=loc_choices)
    to_user = forms.ChoiceField(label='User', choices=user_choices)
    to_dept = forms.ChoiceField(label='Department', choices=dept_choices)
    to_location = forms.ChoiceField(label='Location', choices=loc_choices)
    from_date = forms.DateField(label='Awarded Between', required=False)
    to_date = forms.DateField(label='and', required=False)

iotaProject/administrator/views.py
""" administrator/views.py """

from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.utils import timezone
from teamiota.models import NormalUser
from .reports import Report
from .forms import *
from django.contrib.auth.decorators import user_passes_test


@login_required()
@user_passes_test(lambda u: u.normaluser.isAdmin)
def admin_account(request):
    """ The main Administrator Page """

    return render(request, 'admin_account.html')

@login_required()
@user_passes_test(lambda u: u.normaluser.isAdmin)
def edit(request):
    """ Process email address input from edit.html """

    email = request.POST.get('email', None)

    if email is None:
        return render(request, 'edit.html')
    else:
        try:
            user = User.objects.get(email=email)
            return HttpResponseRedirect(
                '/administrator/edit_user/{0}'.format(user.id))
        except:
            return render(request, 'edit.html', {'noemail': True})

@login_required()
@user_passes_test(lambda u: u.normaluser.isAdmin)
def edit_user(request, user_id):
    """ Handle the submission of the Edit User form """

    user = User.objects.get(id=user_id)
    normal_user = NormalUser.objects.get(user=user)
    user = normal_user.user
    initial_department = normal_user.department.id
    initial_location = normal_user.location.id
    is_admin = normal_user.isAdmin
    if request.method == "POST":
        edit_user_form = EditUserForm(initial_location, initial_department, 
            is_admin, request.POST, instance=user, prefix='user')
        if edit_user_form.is_valid():
            edit_user_form.save()
            new_department = Department.objects\
                .get(pk=edit_user_form.cleaned_data['department'])
            normal_user.department = new_department
            new_location = Location.objects\
                .get(pk=edit_user_form.cleaned_data['location'])
            is_admin = edit_user_form.cleaned_data['is_admin']
            normal_user.isAdmin = is_admin
            normal_user.location = new_location
            normal_user.save()
            return HttpResponseRedirect('/administrator')
    else:
        edit_user_form = EditUserForm(initial_location, initial_department, 
            is_admin, instance=user, prefix='user')

        return render(request, 'edit_user.html',
            {
              'user_to_edit': normal_user,
              'edit_user_form': edit_user_form,
            })

@login_required()
@user_passes_test(lambda u: u.normaluser.isAdmin)
def list(request):
    """ Page with a table of Users """

    users = NormalUser.objects.all()
    return render(request, 'list.html', {'users':users})

@login_required()
@user_passes_test(lambda u: u.normaluser.isAdmin)
def add_user(request):
    """ Add User Page """

    new_normal_user = None
    if request.method == 'POST':  # Admin User submitted Add User Form
    
        # Get input for both the Base User and NormalUser
        add_user_form = AddUserForm(request.POST, prefix='user')

        if add_user_form.is_valid():
        
            # pylint: disable=line-too-long
            # src for last_login: http://stackoverflow.com/questions/33075399/automatically-generating-last-login-and-date-joined-values-for-authuser
            
            # Create a django.auth.User from validated form
            username, email, password = (
                add_user_form.cleaned_data['username'],
                add_user_form.cleaned_data['email'],
                add_user_form.cleaned_data['password'])
       
            new_user = User.objects.create_user(username=username,
                email=email, password=password)
            
            new_user.last_name = add_user_form.cleaned_data['last_name']
            new_user.first_name = add_user_form.cleaned_data['first_name']
            
            # Set last_login
            new_user.last_login = timezone.now()
            new_user.save()
            
            # Modify the associated teamiota.models.NormalUser
            new_normal_user = NormalUser.objects.get(user=new_user)
            new_normal_user.isAdmin = add_user_form.cleaned_data['is_admin']
            new_normal_user.department = Department.objects.get(
                pk=add_user_form.cleaned_data['department'])
            new_normal_user.location = Location.objects.get(
                pk=add_user_form.cleaned_data['location'])
            new_normal_user.save()

    else:
        add_user_form = AddUserForm(prefix='user')

    return render(request, 'add_user.html',
                  {
                      'user_form': add_user_form,
                      'new_normal_user': new_normal_user
                  })

@login_required()
@user_passes_test(lambda u: u.normaluser.isAdmin)
def delete(request, user_id):
    """ Delete a User """

    try:
        user = User.objects.get(id=user_id)
    except:
        return render(
        request, 'list.html', {'users': NormalUser.objects.all()})
    user.delete()
    return render(request, 'list.html', {'users': NormalUser.objects.all()})

@login_required()
@user_passes_test(lambda u: u.normaluser.isAdmin)
def reports(request, report_id):
    """ Handler for all reports """

    this_report = Report(report_id)
    return render(request, this_report.template, {
        'title' : this_report.title,
        'details' : this_report.report_data,
        'summary' : this_report.summary_data,
        'chart' : this_report.chart_data,
        'sort' : this_report.sort_col
    })

@login_required()
@user_passes_test(lambda u: u.normaluser.isAdmin)
def reports_filter(request):
    """ Handler for custom reports """

    # If POST, process form data
    if request.method == 'POST':
        form = ReportFilterForm(request.POST)
        this_report = Report('0')
        if form.is_valid():
            # Create array of filters to apply
            filters = {}
            filters['award_type'] = form.cleaned_data['award_type']
            filters['from_user'] = form.cleaned_data['from_user']
            filters['from_dept'] = form.cleaned_data['from_dept']
            filters['from_location'] = form.cleaned_data['from_location']
            filters['to_user'] = form.cleaned_data['to_user']
            filters['to_dept'] = form.cleaned_data['to_dept']
            filters['to_location'] = form.cleaned_data['to_location']
            filters['from_date'] = form.cleaned_data['from_date']
            filters['to_date'] = form.cleaned_data['to_date']

            # Apply filters to report
            this_report.apply_filters(filters)

        return render(request, this_report.template, {
            'title' : this_report.title,
            'details' : this_report.report_data,
            'summary' : this_report.summary_data,
            'chart' : this_report.chart_data,
            'sort' : this_report.sort_col
        })

    # Else, display blank form
    else:
        form = ReportFilterForm()

    return render(request, 'report_filters.html', {'form' : form})

def logout_user(request):
    """ Handle a User logout request """

    logout(request)
    return HttpResponseRedirect('/administrator')

iotaProject/administrator/templates/add_user.html
{% extends 'base.html' %}

{% block body %}

 {% if not new_normal_user %}
	<form method="POST" action="">
		{% csrf_token %}
		<fieldset>
			<legend>Add New User</legend>	
	
      		{{ user_form.as_p }}

      		{{ upf.as_p }}
			<input type='submit' value="Add User"/>
		</fieldset>      
  	</form>
  {% else %}
     <h5> {{ new_normal_user.nickname }} has been added. </h5>
  {% endif %}

{% endblock %}

iotaProject/administrator/templates/admin_account.html
{% extends 'base.html' %}

{% block body %}

<div container>
	<div tabindex="0" class="dropdown button">
		Manage Accounts &raquo;
		<ul class="collection dropdown-content">
			<div class="collection-item">
				<a href='/administrator/add_user/'><button class="button--xsm">Add User</button></a>
			</div>
  			<div class="collection-item">
  				<a href="/administrator/edit/"><button class="button--xsm">Edit User</button></a>
			</div>
			<div class="collection-item">
				<a href="/administrator/list/"><button class="button--xsm">List Users</button></a>
			</div>
		</ul>
	</div>



	<div tabindex="0" class="dropdown button">
		Reports &raquo;
	<ul class="collection dropdown-content">
	<div class="collection-item">
		<a href='/administrator/reports/1'><button class="button--xsm">Awards by Type</button></a>
	</div>
	<div class="collection-item">
		<a href='/administrator/reports/2'><button class="button--xsm">Awards by Department</button></a>
	</div>
	<div class="collection-item">
		<a href='/administrator/reports/3'><button class="button--xsm">Awards by Location</button></a>
	</div>
	<div class="collection-item">
		<a href='/administrator/reports/4'><button class="button--xsm">Awards this Month</button></a>
	</div>
	<div class="collection-item">
		<a href='/administrator/reports/5'><button class="button--xsm">Awards this Year</button></a>
	</div>
	<div class="collection-item">
		<a href='/administrator/reports/6'><button class="button--xsm">Awards All Time</button></a>
	</div>
	<div class="collection-item">
		<a href='/administrator/reports/7'><button class="button--xsm">Awards Given by User</button></a>
	</div>
	<div class="collection-item">
		<a href='/administrator/reports/8'><button class="button--xsm">Awards Received by User</button></a>
	</div>
	<div class="collection-item">
		<a href='/administrator/reports/custom/'><button class="button--xsm">Custom Report</button></a>
	</div>
	</ul>
</div>
{% endblock %}

iotaProject/administrator/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.concisecss.com/v3.4.0/concise.css">
        <link rel="stylesheet" href="{% static 'administrator/css/reports.css' %}">

        <!-- Resources for reports datepicker -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    </head>

    <body>
    <div container>
        <h2>2016 Team Iota-Employee Recognition Administrator Site</h2>

      <ul class="group">
            <li id="hometab" class="group-item"><a href="{% url 'index' %}">Home</a>
            <li id="logouttab" class="group-item"><a href="{% url 'normalUserLogout' %}">Logout</a>
      </ul>  
    </div>
    <div container>
        {% block body %}
        {% endblock %}
    </div>
    </body>
    </html>

iotaProject/administrator/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" action="">
	<fieldset>
		<legend>Enter email of user to edit</legend>
		{% csrf_token %}
		<p>
     		<label for="email">Existing Email:</label>
    		<input type="text" name="email">
    	</p>
      	<input type='submit' value="Edit User"/>
      </fieldset>
  </form>
  {% if noemail %}
  <h5 class="text--warning">The email you searched for does not exist</h5>
  {% endif %}
{% endblock %}

iotaProject/administrator/templates/edit_user.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" action="">
    {% csrf_token %}
    <fieldset>
    	<legend>Edit {{ user_to_edit.nickname }}</legend>
    	{{ edit_user_form.as_p }}
    	<input type="submit"/>
    </fieldset>
</form>
{% endblock %}

iotaProject/administrator/templates/list.html
{% extends 'base.html' %}
{% block body %}
<h5>List of users</h5>
<table class="table--border">
	<thead>
  		<tr>
  		  <th class="tg-yw4l">Name</th>
  		  <th class="tg-yw4l">Location</th>
  		  <th class="tg-yw4l">Department</th>
  		  <th class="tg-yw4l">Account Type</th>
  		  <th class="tg-yw41">Edit</th>
  		  <th class="tg-yw41">Delete</th>
  		</tr>
	</thead>
	<tbody>
  	{% for user in users %}
  	<tr>
  		<td>{{ user.nickname }}</td>
  		<td>{{ user.location }}</td>
  		<td>{{ user.department }}</td>
  	  {% if user.isAdmin %}
  	  	<td>Admin</td>
    	{% else %}
    		<td>User</td>
    	{% endif %}
	 	<td><a href='/administrator/edit_user/{{user.user.id}}'><button>Edit</button></a></td>
   		<td><a href='#modal'><button id="delete_user_button" class="button--error" data-user-id="{{user.user.id}}">Delete</button></a></td>
  	</tr>
   	{% endfor %}
	</tbody>
</table>

<!-- Modal for delete user confirmation -->
<div id="modal" class="modal">
  <div class="modal-container">
    <div class="modal-header">
      Delete User

      <a href="#close" class="modal-close">&times;</a>
    </div>

    <div class="modal-body">
      <p>This will permanently delete the selected user. Are you sure you want to continue?</p>
    </div>

    <div class="modal-footer">
      <a href="#close" class="modal-close"><button class="button--muted">No</button></a>
      <a id="delete_user_link" href='#'><button class="button--error">Yes</button></a>
    </div>
  </div>
</div>

<!-- Script to pass data from main page to modal -->
<script>
  $(document).on("click", "#delete_user_button", function () {
       var delete_link = "/administrator/delete/" + $(this).attr("data-user-id");
       $("#delete_user_link").attr("href", delete_link);
  });
</script>

{% endblock %}

iotaProject/administrator/templates/login.html
{% extends 'base.html' %}

{% block body %}
<form method="POST" action="" role="form">
  	{% csrf_token %} 
  	<fieldset>
  		<legend>Enter your Administrator Credentials</legend>
  	<p>
  		<label for="username">Username</label>	
		<input type="text" value="" name="username" class="" label='UserName'>
	</p>
	<p>
		<label for="password">Password</label>
		<input id="login-password" type="password" class="" name="password" placeholder="password">
	</p>
	<p>
		<input type="submit" id="btn-login" class="button" value="Login">
	</p>
	</fieldset>
</form>

{% endblock %}

iotaProject/administrator/templates/report_filters.html
{% extends 'base.html' %}

{% block body %}

<script>
	$( function() {
	  $( "#id_from_date" ).datepicker();
	  $( "#id_to_date").datepicker();
	} );
</script>

<form class="form--inline" method="POST" action="">
	{% csrf_token %}
	<fieldset>
		<legend>Report Filters</legend>	

		<!-- General Filters -->
		<fieldset>
			<legend>General</legend>
			<div class="fieldWrapper">
	    		{{ form.award_type.label_tag }}
	    		{{ form.award_type }}
	  		</div>
			<div class="fieldWrapper">
	    		{{ form.from_date.label_tag }}
	    		{{ form.from_date }}
	  		</div>

	  		<div class="fieldWrapper">
	    		{{ form.to_date.label_tag }}
	    		{{ form.to_date }}
	  		</div>
		</fieldset>
	  		

		<!-- Awarder Filters -->
  		<fieldset>
  			<legend>Awarded By</legend>
	  		<div class="fieldWrapper">
	    		{{ form.from_user.label_tag }}
	    		{{ form.from_user }}
	  		</div>

	  		<div class="fieldWrapper">
	    		{{ form.from_dept.label_tag }}
	    		{{ form.from_dept }}
	  		</div>

	  		<div class="fieldWrapper">
	    		{{ form.from_location.label_tag }}
	    		{{ form.from_location }}
	  		</div>
	  	</fieldset>

 		<!-- Awardee Filters -->
		<fieldset>
			<legend>Awarded To</legend>
			<div class="fieldWrapper">
	    		{{ form.to_user.label_tag }}
	    		{{ form.to_user }}
	  		</div>

	  		<div class="fieldWrapper">
	    		{{ form.to_dept.label_tag }}
	    		{{ form.to_dept }}
	  		</div>

	  		<div class="fieldWrapper">
	    		{{ form.to_location.label_tag }}
	    		{{ form.to_location }}
	  		</div>
  		</fieldset>

		<input type='submit' value="Create Report"/>
	</fieldset>      
</form>

{% endblock %}