iotaProject/iotaProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# https://docs.djangoproject.com/en/1.10/topics/auth/default/#using-the-views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
import teamiota.views
from . import settings
import logging
urlpatterns = [
    url(r'^$', teamiota.views.LoginView.as_view()),
    url('^password_reset/$',
        auth_views.password_reset,
        {
            'template_name': 'passwords/password_reset_form.html',
            'email_template_name': 'passwords/password_reset_email.txt',
            'subject_template_name': 'passwords/password_reset_subject.txt',
            'from_email': settings.DEFAULT_FROM_EMAIL,
        },
        name='password_reset'),
    url('^password_reset/done/$',
        auth_views.password_reset_done,
        {
            'template_name': 'passwords/password_reset_done.html',
        },
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {
            'template_name': 'passwords/password_reset_confirm.html',
        },
        name='password_reset_confirm'),
    url('^reset/done/$',
        auth_views.password_reset_complete,
        {
            'template_name': 'passwords/password_reset_complete.html',
        },
        name='password_reset_complete'),
    url(r'^teamiota/', include('teamiota.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^administrator/', include('administrator.urls')),
]
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

iotaProject/teamiota/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.NormalUsersPortal.as_view(), name='normalUsersPortal'),
    url(r'^NormalUsersPortal/', views.NormalUsersPortal.as_view(), name='normalUsersPortal'),
    url(r'^login/', views.LoginView.as_view(), name='normalUserLogin'),
    url(r'^logout/', views.LogoutView.as_view(), name='normalUserLogout'),
    url(r'^award/(?P<pk>[0-9]+)/', views.AwardView.as_view(), name='awardView'),
    url(r'^revoke/', views.RevokeView.as_view(), name='revokeView'),
    url(r'^DrawnSigSubmitted/',
        views.DrawnSigSubmitted.as_view(),
        name='drawnSigSubmitted'),
]

iotaProject/teamiota/models.py
""" teamiota/models.py """

import os
import shutil
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.storage import default_storage as storage
from django.core.urlresolvers import reverse
from django.dispatch.dispatcher import receiver

from iotaProject import settings

from wand.image import Image

class Location(models.Model):
    """ Normal User Location """

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Department(models.Model):
    """ Normal User Department """

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

def signature_path(instance, filename):
    """ Path to save signature image based on id """

    img_path = 'signatures/{0}/sig.png'.\
              format(str(instance.user.id))
    os_path = os.path.join(settings.MEDIA_ROOT, img_path)
    if os.path.exists(os_path):
        os.remove(os_path)
    return img_path

def validate_image(value):
    """ Check extension on uploaded image """

    valid_extensions = ['png', 'jpg', 'jpeg']
    valid = False
    for ending in valid_extensions:
        if value.name.endswith(ending):
            valid = True
    if value.name == '':
        valid = True
    if not valid:
        raise ValidationError(
            u'File type must be one of the following: [' + \
            ', '.join(valid_extensions) + \
            ']. Your file: ' + value.name)

class NormalUser(models.Model):
    """ Additional Profile information for a User """

    user = models.OneToOneField(User, unique=True, default=0, on_delete=models.CASCADE)
    nickname = models.CharField(null=True, blank=True, max_length=50)
    location = models.ForeignKey(Location, null=True, 
                                 on_delete=models.SET_NULL)
    department = models.ForeignKey(Department, null=True, 
                                   on_delete=models.SET_NULL)
    isAdmin = models.BooleanField(default=False)
    signatureImage = models.ImageField(
        upload_to=signature_path,
        validators=[validate_image],
        null=True,
        blank=True)

    def save(self, **kwargs):
        """ Save uploaded signature as 350X100 png sig.png """
        super(NormalUser, self).save()
        # Check for first and last name
        if not self.nickname or self.nickname == '':
            # Set initial nickname to first and last name
            if self.user.first_name or self.user.last_name:
                self.nickname = '{0} {1}'.format(
                    self.user.first_name, self.user.last_name)
            elif self.user.username:
                self.nickname = self.user.username
            elif self.user.email:
                self.nickname = self.user.email.split('@')[0]
            else:
                self.nickname = 'Anonymous'
            self.save(update_fields=['nickname'])
        if self.pk is not None:
            # Signature image was submitted for upload
            if self.signatureImage:
                with storage.open(self.signatureImage.name, 'rb+') as original:
                    with open('temp.png', 'wb+') as temp:
                        shutil.copyfileobj(original, temp)

                with Image(filename='temp.png') as sig:
                    sig.resize(350, 100)
                    sig.format = 'png'
                    sig.save(filename='temp.png')

                with storage.open(self.signatureImage.name, 'wb+') as resized:
                    with open('temp.png', 'rb+') as temp:
                        shutil.copyfileobj(temp, resized)
                os.remove('temp.png')

    def __str__(self):
        return self.user.email

class Award(models.Model):
    """ A Certificate """

    awardTemplate = models.CharField(max_length=1024)
    awardType = models.CharField(max_length=50)

    def __str__(self):
        return self.awardType

def ae_path(instance, filename):
    """ Generate filepath for a certificate image """

    retval = 'teamiota/certThumbs/{0}.{1}'.format(instance.id, 'png')
    return retval

class AwardEvent(models.Model):
    """ Meta Data for an instance of an Award being awarded """

    awarder = models.ForeignKey(
        NormalUser,
        related_name='awardER',
        null=True,
        on_delete=models.CASCADE)
    awardee = models.ForeignKey(
        NormalUser,
        related_name='awardEE',
        on_delete=models.CASCADE)
    awardType = models.ForeignKey(Award, on_delete=models.CASCADE)
    dateOfAward = models.DateField()
    certThumbnail = models.ImageField(upload_to=ae_path, null=True)

    def get_absolute_url(self):
        """ AwardEvent URL opens dialog with apropriate image and links """

        return reverse('awardView', kwargs={'pk': str(self.id)})

    def __str__(self):
        return '{0} awarded {1} to {2}'.\
               format(
                   self.awarder.user.email,
                   self.awardType.awardType,
                   self.awardee.user.email)

# Create a NormalUser on new User object
def create_normal_user(sender, instance, created, **kwargs):
    """ Automatically generate NormalUser on new User """

    if created:
        NormalUser.objects.create(user=instance)

# Attach post_save event handler to User save
models.signals.post_save.connect(create_normal_user, sender=User)

# pylint: disable=line-too-long
# src: http://stackoverflow.com/questions/5372934/how-do-i-get-django-admin-to-delete-files-when-i-remove-an-object-from-the-datab
@receiver(models.signals.pre_delete, sender=AwardEvent)
def mymodel_delete(sender, instance, **kwargs):
    """ Delete certificate thumbnail on AwardEvent deletion """

    if os.path.exists(os.path.join(settings.MEDIA_ROOT, str(instance.id) + '.pdf')):
        os.remove(os.path.join(settings.MEDIA_ROOT, str(instance.id) + '.pdf'))
    if os.path.exists(os.path.join(settings.MEDIA_ROOT, str(instance.id) + '.png')):
        os.remove(os.path.join(settings.MEDIA_ROOT, str(instance.id) + '.png'))
    # Pass false so FileField doesn't save the model.
    instance.certThumbnail.delete(False)

iotaProject/teamiota/forms.py
""" teamiota/forms.py """

from django import forms
from django.contrib.auth.hashers import check_password
from django.contrib.auth import authenticate
from django.db.models import Q
from teamiota.models import User, NormalUser, AwardEvent

class SignatureWidget(forms.widgets.ClearableFileInput):
    """ Add correct URLs to ClearableFileInput template """

    template_with_initial = (
        '%(initial_text)s: <a href="%(initial_url)s"><img src="%(initial_url)s"></a> '
        '%(clear_template)s<br />%(input_text)s: %(input)s'
    )

class NormalUserLoginForm(forms.Form):
    """ Login Form for Normal Users Portal """

    email = forms.EmailField(label='Email:', max_length=50)
    password = forms.CharField(
        label='Password:',
        max_length=50,
        widget=forms.PasswordInput)

    def get_user(self):
        """ Return valid User """

        this_user = User.objects.get(Q(email=self.email))
        username = this_user.get_username()
        return authenticate(username=username, password=self.password)

    def is_valid(self):
        """
        Override default form validation to check user email/pass
        @return None or User object
        """

        # src chriskief.com/2012/12/16/override-django-form-is-valid
        # run default form validation
        is_valid = super(NormalUserLoginForm, self).is_valid()

        # Basic input problems
        if not is_valid:
            return False

        self.email = self.cleaned_data['email']
        self.password = self.cleaned_data['password']

        # Retrieve User from db
        try:
            this_user = User.objects.get(
                Q(email=self.email)
            )

        # Email not in DB
        except User.DoesNotExist:
            self.add_error('email', 'User does not exist')
            return False

        # Password is incorrect for existing email
        if not check_password(self.password, this_user.password):
            self.add_error('password', 'Password is invalid')
            return False

        return True

class NormalUserEditForm(forms.ModelForm):
    """ Edit Form for Normal User """
    
    def __init__(self, *args, **kwargs):
        super(NormalUserEditForm, self).__init__(*args, **kwargs)
        self.fields['nickname'].required = True
    
    class Meta:
        """ Modify form to include only nickname and signatureImage """
        
        model = NormalUser
        fields = ['nickname', 'signatureImage']
        widgets = {
            'signatureImage': SignatureWidget()
        }

class NewAwardForm(forms.ModelForm):
    """ Form for creating a new award """

    def __init__(self, *args, **kwargs):
        super(NewAwardForm, self).__init__(*args, **kwargs)
        self.fields['awardee'].queryset = NormalUser.objects.filter(isAdmin=False)
        self.fields['awardee'].required = True
        self.fields['awardType'].required = True

    class Meta:
        """ Modify form to include only awarder, awardee, awardType and date """

        model = AwardEvent
        fields = ['awarder', 'awardee', 'awardType', 'dateOfAward']

        widgets = {
            'awarder': forms.HiddenInput(),
            'dateOfAward': forms.TextInput(attrs={'class': 'form-control'}),
        }

iotaProject/teamiota/templates/teamiota/normalUser/awardEvent.html
{% load staticfiles %}
<script>
    // Prints the current certificate in landscape mode, using the browser's print interface

    // src: http://stackoverflow.com/questions/2909033/
    // using-javascript-to-print-imageshttp://stackoverflow.com/
    // questions/2909033/using-javascript-to-print-images

    // The following html is loaded into a new window
    // "</scri" + "pt>" to avoid the js from being parsed in the wrong context
    function ImagetoPrint(source) {
        // HTML return code below except <img>, is mostly from src above.
        // Allow time to load the window and print dialog, then close window.
        return "<head><script>function step1(){\
            setTimeout('step2()', 10);}\
            function step2(){window.print();window.close()}\
            </scri" + "pt></head><body onload='step1()'>\
            <img style=\" @page { size: landscape; } height: 100%; width: auto;\" src=\"{{ certImg }}\" /></body>";
    }

    // Open a new window, load html, load print dialog, close new window
    var printCert = function printCert() {
        Pagelink = "about:blank";
        var pwa = window.open(Pagelink, "_new");
        pwa.document.open();
        pwa.document.write(ImagetoPrint());
        pwa.document.close();
    }
</script>

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">{{ object }}</h4>
        </div>
        <div class="container-fluid">

                <img class="img-responsive" id="img" src="{{ certImg }}">

            <div class="row" style="padding-bottom: 30px;">
                <div class="col-md-2 col-lg-2"></div>
                <div class="col-md-3 col-lg-3">    
                    <button id="printbtn"  type="button" class="btn btn-info btn-lg">Print Certificate</button>
                </div>
                <div class="col-md-2 col-lg-2"></div>
                <div class="col-md-3 col-lg-3">
                    <a  href="{{ certPDF }}" download>
                        <button id="savebtn" type="submit" class="btn btn-info btn-lg">Save PDF</button>
                    </a>
                </div>
                <div class="col-md-2 col-lg-2"></div>
            </div>
            
            <script>
                $(function() {
                    $("#printbtn").click(
                        function() {
                            printCert();
                        });
                    });
            </script>
        </div>
    </div>
</div>

iotaProject/teamiota/templates/teamiota/normalUser/awardGrid.html
{% load staticfiles %}
<script>
	var getAwardDetail = function(thisAwardURL) {
		$.ajax({url: thisAwardURL}).done(function(success) {
			$("#awardDetailModal").html(success);
			$("#awardDetailModal").modal('show');
		});
	}
</script>
<div class="container">
<div id="awardDetailModal" class="modal" role="dialog"></div>
</div>
<div class="container">
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Your Awards</h3>
	</div>
	<div class="panel-body">
	<div class="container-fluid">		
	
		{% regroup awardList by awardType as deDupedAwards %}
		{% for awardType in deDupedAwards %}
			<div class="row">
				<h4>{{ awardType.grouper }} <span class="label label-default">{{ awardType.list | length }}</span></h4>
				{% for award in awardType.list %}
					<div class="col-xs-6 col-md-3" id="ae_{{ award.id }}">
						<a {#href="{{ award.get_absolute_url }}"#} class="thumbnail">
							<img class="img-responsive center-block"  src="{{ award.certThumbnail.url }}">
						</a>
					</div>
					<script>
						$(function() {
							$("#ae_{{ award.id }}").click(
								function() {
									thisAwardURL = "{{ award.get_absolute_url }}";
									getAwardDetail(thisAwardURL);
								});
							});
					</script>
				{% endfor %}
			</div>
		{% endfor %}
		<div class="row">
			<div class="col-md-2 col-lg-2"></div>
			<div class="col-md-3 col-lg-3">
				<button id="newAwardbtn" type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#newAwardDialogModal">Award Someone</button>
			</div>
			<div class="col-md-1 col-lg-1"></div>
			<div class="col-md-3 col-lg-3">
				<button id="revokebtn" type="button" data-toggle="modal" data-target="#revokeAlertModal" class="btn btn-danger btn-lg">Revoke Awards</button>
			</div>
			<div class="col-md-2 col-lg-2"></div>
		</div>
	</div>
	</div>
</div>
</div>

iotaProject/teamiota/templates/teamiota/normalUser/basePage.html
{% load staticfiles %}

<!DOCTYPE html>

<html>
    <head>
        <link rel="shortcut icon" type="image/ico" href="{% static 'teamiota/favicon.ico' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>   
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

        {# for signature-pad #}
        <script src="{% static 'teamiota/signature-pad/jquery.signaturepad.js' %}"></script>
        <script src="{% static 'teamiota/signature-pad/assets/json2.min.js' %}"></script>
        <script src="{% static 'teamiota/signature-pad/assets/flashcanvas.js' %}"></script>
        <link rel="stylesheet" href="{% static 'teamiota/signature-pad/assets/jquery.signaturepad.css' %}">
        <title>{% block title %}{% endblock %}</title>
    </head>
    {# src for body_class idea: stackoverflow.com/questions/14781281/django-template-is-extended-teamplate-able-to-change-css-in-parent-page #}
    <body class="{% block body_class %}{% endblock %}">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="#" class="navbar-left"><img height="60px" src="{% static 'teamiota/iotaLogo.png' %}"></a>
                    <h2 class="navbar-text">{% block pageType %} {% endblock %}{% if userName %} for {% else %} {% endif %}{% block userName %} {% endblock %}</h2>
                </div>
                <ul class="nav navbar-right">
                    <li class="dropdown">
                            <button type="button" class="btn btn-lg btn-default dropdown-toggle navbar-btn" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-cog"></span><span>  </span><span class="caret"></span>
                            </button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a data-toggle="modal" data-target="#editFormModal" href="#">Settings</a>
                            <li><a data-toggle="modal" data-target="#drawSignatureModal" href="#">Draw Signature</a>
                            <li><a href="{% url 'normalUserLogout' %}">Log Out</a>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="page-header">
        </div>
        {% block body_block %}{% endblock %} 
        {% include 'teamiota/normalUser/editDialogModal.html' %}
        {% include 'teamiota/normalUser/drawSignatureModal.html' %}
    </body>
</html>

iotaProject/teamiota/templates/teamiota/normalUser/drawSignatureModal.html
{% load i18n widget_tweaks %}
<div class="modal" id="drawSignatureModal">
<div class="modal-dialog modal-dialog" role="dialog">
	<div class="modal-content" id="sigContentContainer">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">Draw Your Signature</h4>
		</div>

		<form method="post" id="drawSigForm" enctype="multipart/form-data" action="{% url 'normalUsersPortal' %}">
			{% csrf_token %}
			<div class="sigPad">
	    		<canvas class="pad" width="350" height="100"></canvas>
	    		<input type="hidden" id="imgOutput" name="imgOutput">
	    		<a href="#clear"><button id="clearbutton" class="clearbutton" type="button">Clear</button></a>
	    		
			</div>
    		<div class="modal-footer">
    			<img id="sigImg">
    			
    			<button type="submit" class="btn btn-primary">Save This Signature</button>
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
			</div>
		</form>
	</div>
</div>
</div>

<script>

$(function(){
	if (!window.chrome) {
		$('#clearbutton').click(function() {
			location.reload();
		});
	}
})


var pad = $('.sigPad').signaturePad({drawOnly:true});

$('#drawSigForm').submit(function(e) {
	var img = pad.getSignatureImage();
	$('#imgOutput').attr('value', img);
	var url = "{% url 'drawnSigSubmitted' %}";
		$.ajax({
		type: "POST",
		url: url, 
		data: $('#drawSigForm').serialize(),
		contentType: "application/x-www-form-urlencoded",
		success: function(data)
		{
			$('#sigContentContainer').html(data);
		}
	});
	e.preventDefault();
});
</script>

iotaProject/teamiota/templates/teamiota/normalUser/drawSignatureSuccess.html
<div class="container">
<h4>Your signature was saved:</h4>
</div>
		
<div class="modal-footer">
	<button type="button" class="btn btn-Primary" id="confirmSaved" data-dismiss="modal">Ok</button>
</div>

<script>
	$('#confirmSaved').click(function(){
		location.reload();
	});
</script>

iotaProject/teamiota/templates/teamiota/normalUser/home.html
{% extends 'teamiota/normalUser/basePage.html' %}
{% block body_class %}normalUserHomeBody{% endblock %}
{% block title %}Normal User Home{% endblock %}
{% block pageType %}Home Page{% endblock %} {% block userName %}{{ NormalUser.user }}{% endblock %}
{% block body_block %}

{% include 'teamiota/normalUser/awardGrid.html' %}
	

{% include 'teamiota/normalUser/newAwardDialogModal.html' %}
{% include 'teamiota/normalUser/revokeAlertModal.html' %}

{% endblock %}

iotaProject/teamiota/templates/teamiota/normalUser/newAwardDialogModal.html
{% load i18n widget_tweaks %}
<div id="newAwardDialogModal" class="modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Award Someone</h4>
            </div>
            <form class="form-horizontal" role="form" method="post" action="{% url 'normalUsersPortal'%}">
                {% csrf_token %}
                {% if newAwardForm.awardee.errors %}
                <div class="form-group has-error">
                    <label class="col-sm-2 control-label"for="awardees">{{ newAwardForm.awardee.label }}</label>
                    <div class="col-sm-10">
                        <select name="awardee" class="form-control" id="awardees">
                            {% for awardee in newAwardForm.awardee.field.choices %}
                            <option value="{{ awardee.0 }}">{{ awardee.1 }}</option>
                            {% endfor %}
                        </select>
                        <span class="help-block">
                            {% for error in newAwardForm.awardee.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
                {% else %}
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="awardee">{{ newAwardForm.awardee.label }}</label>
                    <div class="col-sm-10">
                        <select name="awardee" class="form-control" id="awardees">
                        {% for awardee in newAwardForm.awardee.field.choices %}
                        <option value="{{ awardee.0 }}">{{ awardee.1 }}</option>
                        {% endfor %}
                        </select>
                    </div>
                </div>
                {% endif %}
                {% if newAwardForm.awardType.errors %}
                <div class="form-group has-error">
                    <label class="col-sm-2 control-label" for="awardType">Award Type: </label>
                    <div class="col-sm-10">
                        <select name="awardType" class="form-control" id="awardType">
                            {% for awardType in newAwardForm.awardType.field.choices %}
                                <option value="{{ awardType.0 }}">{{ awardType.1 }}</option>
                            {% endfor %}
                        </select>
                        <span class="help-block">
                            {% for error in newAwardForm.awardType.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
                {% else %}
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="awardType">Award Type: </label>
                    <div class="col-sm-10">
                    <select name="awardType" class="form-control" id="awardType">
                        {% for awardType in newAwardForm.awardType.field.choices %}
                            <option value="{{ awardType.0 }}">{{ awardType.1 }}</option>
                        {% endfor %}
                    </select>
                    </div>
                </div>
                {% endif %}
                {{ newAwardForm.awarder }}
                {% if newAwardForm.dateOfAward.errors %}
                <div class="form-group has-error">
                    <label class="col-sm-2 control-label" for="id_dateOfAward">{{ newAwardForm.dateOfAward.field.label }}</label>
                    <div class="col-sm-10">
                        <div class="input-group date" id="datetimepicker1">
                               {{ newAwardForm.dateOfAward }}
                               <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                               <span class="help-block">
                                   {% for error in  newAwardForm.dateOfAward.errors %}{{ error }}{% endfor %}
                               </span>
                           </div>
                    </div>
                </div>
                {% else %}
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="id_dateOfAward">{{ newAwardForm.dateOfAward.field.label }}</label>
                    <div class="col-sm-10">
                        <div class="input-group date" id="datetimepicker1">
                            {{ newAwardForm.dateOfAward }}
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                           </div>
                    </div>
                </div>
                {% endif %}
                <script type="text/javascript">
                    $(function() {
                        $("#datetimepicker1").datetimepicker({format: 'MM/DD/YYYY'});
                    });
                </script>
                <div class="modal-footer">
                    <button type="button" class="btn btn-responsive btn-info" data-dismiss="modal">Cancel</button>
                    <button id="newAwardSubmitbtn"></button>
                </div>
                <script>
                    var loadAwardButton = function(){
                        if ("{{ hasSig }}" === "true") {
                            $("#newAwardSubmitbtn").attr({
                                "type": "submit",
                                "value": "Submit",
                                "name": "newAwardForm",
                                "class": "btn btn-responsive btn-primary",
                                "innerText": "Submit"
                                });
                                $("#newAwardSubmitbtn").text("Submit");
                        } else {
                            $("#newAwardSubmitbtn").attr({
                                "class": "btn btn-responsive btn-danger",
                                "type": "button",
                                "innerText": "Locked: Upload a signature image"
                            });
                            $("#newAwardSubmitbtn").text("Locked: Upload a signature image");
                        }
                    }
                    loadAwardButton();
                    if ("{{ showAwardForm }}" === "true"){
                        $(window).load(function() {
                            $('#newAwardDialogModal').modal('show');
                        });
                    }
            </script>
            </form>
        </div>
    </div>
</div>

iotaProject/teamiota/templates/teamiota/normalUser/revokeAlertModal.html
<div id="revokeAlertModal" class="modal fade" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Are You Sure?</h4>
			</div>
			<div class="modal-body">
				<p>By clicking "Accept", you agree to revoke all certificates you have previously awarded.</p>
				<div class="row">
					<div class="col-md-4 col-lg-4"></div>
					<div class="col-md-4 col-lg-4">
						<a href="{% url 'revokeView' %}">
							<button class="btn btn-lg btn-danger">Accept</button>
						</a>
					</div>
					<div class="col-md-4 col-lg-4"></div>
				</div>
			</div>
		</div>
	</div>
</div>